interval = 300
report_to_stdout = true

[chef_license]
acceptance = "undefined"

# Uncomment and replace values to report to Automate.
# This can also be applied at runtime via `hab config apply`
# [automate]
# url = 'https://<automate_url>'
# token = '<automate_token>'
# user = '<automate_user>'